Hotel_Ordering_Application/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import default_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Restaurant.urls')),
    path('', default_home, name='default_home_name'),
    path('accounts/', include('accounts.url')),
    path('verification/', include('verify_email.urls')),
    path('wallet/', include('wallet.url'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Restaurant/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.food, name="food"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('product/description/<str:id>', views.product_info, name="product_description_page"),
    path('update_item/', views.updateItem, name="update_item"),
    path('previous/order', views.prev_orders, name="prev_orders"),
    path('previous/items/<str:id>', views.prev_items, name="prev_items"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.
#comment for commit
GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]


class CustomUser(AbstractUser):
    name = models.CharField(max_length=50,null=True,blank=True)
    email = models.EmailField(unique=True)
    Gender = models.CharField(max_length=6, choices=GENDER_CHOICES,default='Male')
    Birthday = models.DateTimeField(null=True,blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits "
                                         "allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    profile_pic = models.ImageField(default="default.png",null=True, blank=True)
    proof = models.ImageField(default="default_proof.JPG",blank=True,null=True)
    address1 = models.CharField(max_length=100, blank=True, null=True)
    address2 = models.CharField(max_length=100, blank=True, null=True)
    pin_code = models.CharField(max_length=12, blank=True, null=True)
    city = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=12, blank=True, null=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.contrib.auth.forms import UserCreationForm
from .form import CustomUserCreationForm, settigs_form, update_profile_form, passwordchangingform
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from .decorators import unauthenticated_user
from django.contrib.auth.decorators import login_required
from verify_email.email_handler import send_verification_email

from django.contrib.auth.models import Group
import re


# Create your views here.

def hello_world(request):
    return render(request, 'accounts/home.html')


@unauthenticated_user
def login_views(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('default_home_name')
            # return HttpResponse(f'hello {request.user}')
        else:
            messages.info(request, "username or password is incorrect")
    context = {}
    return render(request, 'accounts/loginPage.html', context)


@unauthenticated_user
def register_views(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        print()
        if form.is_valid():
            inactive_user = send_verification_email(request, form)
            # form.save()
            # user = form.save(commit=False)
            # user.save()

            user_name = form.cleaned_data.get('username')
            print(user_name)
            messages.success(request, 'Account was successfully created for ' + user_name + ' Email sent to your mail')
            return redirect('login_page')

        # else:
        #
        #     # messages.error(request, f'Account was unsuccessfully created {form.error_messages}')
        #     return redirect('register_page')
    context = {'form': form}
    return render(request, 'accounts/registerPage.html', context)

@login_required(login_url='login_page')
def logout_view(request):
    logout(request)
    messages.success(request, 'You are successfully logged out')
    return redirect('login_page')

@login_required(login_url='login_page')
def default_home(request):
    print('default_home')
    group = None

    if request.user.groups.exists():
        group = request.user.groups.all()[0].name
        print(group)

        if group == 'customer':
            # return redirect('customer_home')
            return redirect('hello')

        elif group == 'manager':
            # return redirect('manager_home')
            return redirect('hello')
        elif group == 'chef':
            # return redirect('chef_home')
            return redirect('hello')

        else:
            message = "You are not authorized to view this page"
            messages.error(request, message)
            return redirect('logout_page')
        # return HttpResponse('You are not authorized to view this page')
    else:
        print("home page")
        return redirect('food')

@login_required(login_url='login_page')
def settings_view(request):
    userr = request.user
    form = settigs_form(instance=userr)
    if request.method == 'POST':
        form = settigs_form(request.POST, request.FILES, instance=userr)
        if form.is_valid():
            form.save()
            return redirect('food')
        # else:
        #     return redirect('settings')
    context = {'form': form}
    return render(request, 'accounts/settings.html', context)

@login_required(login_url='login_page')
def update_profile_view(request):
    user_pic = request.user
    form = update_profile_form(instance=user_pic)
    if request.method == "POST":
        form = update_profile_form(request.POST, request.FILES, instance=user_pic)
        user_pic.profile_pic.delete(save=True)
        if form.is_valid():
            form.save()
            return redirect('settings')
        else:
            return redirect('update_profile_pic')
    context = {"form": form}
    return render(request, "accounts/update_profile_pic.html", context)


class update_password(PasswordChangeView):
    form_class = passwordchangingform
    # messages.add_message(self.request, messages.INFO, 'Hello world.')
    success_message = "Your Password was successfully Changed!"
    success_url = reverse_lazy('settings')

accounts/templates/accounts/home.html
{% extends 'accounts/main.html' %}

{% block content %}
<h1>Hii this is Home Page! </h1>

{% endblock %}

accounts/templates/accounts/loginPage.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'register_page' %}" class="ml-2">Sign Up</a>
                </div>

            </div>
        </div>
    </div>
</div>
</body>

</html>

accounts/templates/accounts/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Hotel Management System</title>
    <script src="{% static 'js/realtime.js' %}"></script>
    <link rel="stylesheet" type="text/css" href={% static 'css/main.css' %}>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
          integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
            integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
</head>
<body onload="realtimeclock()">
{% include 'accounts/navbar.html' %}
{% block content %}


{% endblock %}
<hr>
<h5>Footer</h5>
</body>
</html>

accounts/templates/accounts/navbar.html
<style>
    .hello-msg {
        font-size: 20px;
        color: white;
        margin-right: 20px;
    }

    .logout-msg {
        font-size: 15px;
        color: gainsboro;
        margin-right: 10px;
    }
    .time-msg{
        font-size: 15px;
        color: white;
        margin-right: 10px;
    }
</style>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'food' %}">Home </a>
            <a class="nav-item nav-link active" href="{% url 'settings' %}">settings</a>
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
    </div>
{#    <span class="logout-msg">{% now "jS - F - Y  H:i:s" %}</span>#}
    <span><div id="clock" class="time-msg"><p>Time is precious.</p></div></span>
    <span class="hello-msg">Hello, {{ request.user }}</span>
    <span><a class="logout-msg" href="{% url 'logout_page' %}"> Logout</a></span>
</nav>

accounts/templates/accounts/registerPage.html
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #7abecc !important;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            color: #fff;
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }

    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">REGISTER ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>


                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>

                </form>
            </div>

            <br>
            <div>

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-primary" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-primary" role="alert">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
            </div>

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'Email..';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>
</body>
</html>

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>register</title>#}
{#</head>#}
{#<body>#}
{#<h3>register</h3>#}
{#<form action="" method="POST" >#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <input type="submit" name="create">#}
{##}
{#</form>#}
{##}
{#</body>#}
{#</html>#}

accounts/templates/accounts/settings.html
{% extends 'Restaurant/main.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <script>
        $(function () {
            $("#id_Birthday").datetimepicker({
                format: 'd/m/Y H:i',
            });
        });
    </script>
    <style>
        .profile-pic {
            max-width: 200px;
            max-height: 200px;
            margin: 0 auto;
            border-radius: 50%;
        }

        .proof-pic {
            max-width: 100px;
            max-height: 100px;
            margin: 0 auto;
            overflow: hidden;
        }
    </style>
    <div style='margin-top:5px;margin-left:10px;margin-right:10px;'>
        <div class="row">
            <div class="col-md-3">
                <div class="card card-body">
                    <a class="btn btn-warning" href="{% url 'update_profile_pic' %}"> &#8592; update profile</a>
                    <hr>
                    <h3 style="text-align: center">Account Settings</h3>
                    <hr>
                    <img class="profile-pic" src="{{ request.user.profile_pic.url }}">
                </div>
            </div>
        </div>
    </div>
    <div style='margin-top:5px;margin-left:10px;margin-right:10px;'>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-3">
                    {{ form.name|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.Gender|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.Birthday|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    {{ form.phone_number|as_crispy_field }}
                </div>

                <div class="col-3">
                    {{ form.address1|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.address2|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.pin_code|as_crispy_field }}
                </div>
            </div>
            <div class="row">

                <div class="col-2">
                    {{ form.city|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.country|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.proof|as_crispy_field }}
                    <img class="proof-pic" src="{{ request.user.proof.url }}">
                </div>
                <div class="col-3">
                    <a class="btn btn-warning" href="{% url 'update_password' %}">update password</a>
                </div>
            </div>
            {{ form.errors }}
            <br>
            <input class="btn btn-primary" type="submit" name="save">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "Restaurant/main.html" %}
{% load static %}
{% block title %} Change Password {% endblock %}
{% block content %}
    <div class="form-group" style="margin:15px 10px 10px 25px ; width:30%">
<form method="post">
{% csrf_token %}
{{ form.as_p}}
<button class="btn btn-primary">change password</button>
</form>
        <br>
        <hr>
    <ul>
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    </div>
{% endblock %}

accounts/templates/accounts/update_profile_pic.html
{% extends "accounts/main.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" name="save">
    </form>
{% endblock %}